# Generated by Django 4.2.2 on 2023-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBrecha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus")],
                default="Free",
                max_length=10,
            ),
        ),
    ]
