# Generated by Django 4.2.2 on 2023-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBrecha", "0002_alter_contact_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus")], max_length=10
            ),
        ),
    ]
